version: 0.1
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/unpack.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root
